"""init

Revision ID: ded1b0d304dd
Revises: 8e9c46887a13
Create Date: 2021-04-16 04:11:11.726937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded1b0d304dd'
down_revision = '8e9c46887a13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edit_triplet', sa.String(length=256), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestions_edit_triplet'), 'suggestions', ['edit_triplet'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suggestions_edit_triplet'), table_name='suggestions')
    op.drop_table('suggestions')
    # ### end Alembic commands ###
